version: 2
jobs:
  install:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: npm-deps-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "package-lock.json" }}

  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: curl --silent https://v4.ifconfig.co/
      - run:
          name: Installing dependencies
          command: npm ci
      - run:
          name: Run tests
          command: npm run all-with-coverage
      - save_cache:
          key: npm-deps-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run coveralls
          command: npm run coveralls
          when: on_success

workflows:
  version: 2
  workflow:
    jobs:
      - install
      - test:
          requires:
            - install
