common: &common
  docker:
    - image: circleci/node:lts
  steps:
    - checkout
    - run: node --version
    - run: npm --version
    - run: curl --silent https://v4.ifconfig.co/
    - restore_cache:
        key: npm-deps-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "package-lock.json" }}
    - run: npm ci
    - save_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
        paths:
          - /home/circleci/project/
    - save_cache:
        key: npm-deps-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "package-lock.json" }}
        paths:
          - /home/circleci/.npm

version: 2
jobs:
  install:
    <<: *common

  test:
    <<: *common
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run tests
          command: npm run test-with-coverage
      - run:
          name: Run coveralls
          command: npm run coveralls
          when: on_success

  test-functional-debug:
    <<: *common
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run functional tests (debug)
          command: npm run mocha:only-functional:dev

  test-functional-prod:
    <<: *common
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run functional tests (production)
          command: npm run mocha:only-functional:prod

workflows:
  version: 2
  install-and-test:
    jobs:
      - install
      - test:
          requires:
            - install
      - test-functional-debug:
          requires:
            - install
      - test-functional-prod:
          requires:
            - install
