version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts-stretch
    steps:
      - checkout

      - restore_cache:
          key: npm-deps-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "package-lock.json" }}

      - run:
          name: Get runner's IP in case we need to debug CDN failures
          command: curl --silent https://v4.ifconfig.co/

      - run:
          name: Installing dependencies
          command: npm ci

      - run:
          name: Run all tests
          command: npm run all-with-coverage

      - save_cache:
          key: npm-deps-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm

# todo Coveralls
