version: 2

common_image: &common_image
  docker:
    - image: circleci/node:10

common_steps: &common_steps
  steps:
    - checkout
    - run: node --version
    - run: npm --version
    - run: curl --silent https://v4.ifconfig.co/
    - restore_cache:
        key: npm-deps-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "package-lock.json" }}
    - run: npm ci
    - save_cache:
        key: npm-deps-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "package-lock.json" }}
        paths:
          - /home/circleci/.npm

jobs:
  test:
    <<: *common_image
    <<: *common_steps
    steps:
      - run:
          name: Run tests
          command: npm run test-with-coverage
      - run:
          name: Run coveralls
          command: npm run coveralls
          when: on_success

  test-functional-debug:
    <<: *common_image
    <<: *common_steps
    steps:
      - run:
          name: Run functional tests (debug)
          command: npm run mocha:only-functional:dev

  test-functional-prod:
    <<: *common_image
    <<: *common_steps
    steps:
      - run:
          name: Run functional tests (production)
          command: npm run mocha:only-functional:prod

workflows:
  version: 2
  test:
    jobs:
      - test
      - test-functional-debug
      - test-functional-prod
